server:
    port: 9002
    context-path: /user-address

spring:
    application:
        name: user-address
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    logging:
        pattern:
            console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
        level:
            ROOT: DEBUG
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/user_address
        username: postgresql
        password: postgresql
        hikari:
            minimumiIdle: 5
            maximum-pool-size: 20
            idle-timeout: 30000
            pool-name: SpringBootJPAHikariCP
            max-lifetime: 2000000
            connection-timeout: 30000
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 10.11.57.9:9092, 10.11.57.9:9098
                    zkNodes: 10.11.57.9:2181
                    replicationFactor: 2
            bindings:
                user-output:
                    destination: kafka-benchmark.user-output
                    group: user-outbound
                    contentType: application/json
                    partitionCount: 2
                user-address-output:
                    destination: kafka-benchmark.user-address-output
                    group: user-address
                    contentType: application/json